version: '3.8'

services:
  backend:
    build:
      context: ./Back-end
    ports:
      - "5000:5000"
    volumes:
      - ./Back-end:/app
    restart: always

  frontend:
    build:
      context: ./Front-end/Spelling Bee
    ports:
      - "3000:80"
    restart: always
